### ISSUE TITLE
Issue  with compiling and I have the latest dependencies

### ISSUE THREAD

**Issue by palontologist** [Startup-Landing/Startup-Landing#11]
ready - started server on http://localhost:3000
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported

**Comment by palontologist** [comment]
can you guys please add this to documentation

**Comment by kinov777** [comment]
After running npm run dev in the project. It gives me error please help me and resolve it. Thanks


PS C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next> npm run dev   
   
> @landing/006-next@0.1.0 dev
> next dev

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\honey\Downloads\agency-minimal-next\006-agency-minimal-next\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0

**Comment by LucasBonafe** [comment]
> ready - started server on http://localhost:3000 Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db node:internal/crypto/hash:71 this[kHandle] = new _Hash(algorithm, xofLen); ^
> 
> Error: error:0308010C:digital envelope routines::unsupported

Solved?
