### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Glebuar** [Startup-Landing/Startup-Landing#6]
Agency Modern Next.js Template 

`yarn build`:
```
./node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

./node_modules/next/dist/next-server/server/require.js
Critical dependency: the request of a dependency is an expression

info  - Collecting page data
[    ] info  - Generating static pages (1/2)Unhandled error during request: ReferenceError: window is not defined
    at new ModalVideo (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:4796:76)
    at d (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8913:320)
    at $a (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8916:16)
    at a.b.render (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8921:476)
    at a.b.read (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8921:18)
    at renderToString (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8931:364)
    at Object.renderPage (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:1293:851)
    at Function.getInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:27319:19)
    at Function.getInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:41165:85)
    at loadGetInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:32998:27)

Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
ReferenceError: window is not defined
    at new ModalVideo (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:4796:76)
    at d (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8913:320)
    at $a (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8916:16)
    at a.b.render (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8921:476)
    at a.b.read (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8921:18)
    at renderToString (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:8931:364)
    at Object.renderPage (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:1293:851)
    at Function.getInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:27319:19)
    at Function.getInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:41165:85)
    at loadGetInitialProps (/mnt/c/Users/Gleb/Desktop/agency/.next/serverless/pages/index.js:32998:27)
info  - Generating static pages (2/2)

> Build error occurred
Error: Export encountered errors on following paths:
        /
    at exportApp (/mnt/c/Users/Gleb/Desktop/agency/node_modules/next/dist/export/index.js:24:1103)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async build (/mnt/c/Users/Gleb/Desktop/agency/node_modules/next/dist/build/index.js:37:212)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn dev`:
```
1 of 1 unhandled error
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/_document.tsx (91:33) @ Function.getInitialProps

  89 |     }
  90 | 
> 91 |     const { html, head } = await ctx.renderPage({ enhanceApp })
     |                                 ^
  92 |     const styles = [...flush()]
  93 |     return { html, head, styles }
  94 |   }
Call Stack
Function.getInitialProps
src/pages/_document.js (5:40)
```

**Comment by YukiOta** [comment]
The same things happened when I tried to use Online Course Next.js template, and I fixed it by changing the version of `react-modal-video` to `1.2.6` for now.

```
-    "react-modal-video": "^1.2.6",
+    "react-modal-video": "1.2.6",
```

This is discussed here too: https://github.com/appleple/react-modal-video/issues/64

**Comment by paulruet** [comment]
This issue is fixed in the latest updates.
 Thanks
